---
title: Corporations database
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Jason
email: jason54@gmail.com
description: 'database of corporations

'
twitter_username: macrod68
github_username: macrod68
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
